# Site settings
title: Cherry.js Home Page
email: zry656565@gmail.com
description: "Home page for Cherry.js"
baseurl: ""
url: "http://cherryjs.com"

# Build settings
markdown: kramdown
permalink: pretty
