site_name: Cherry.js
site_url: http://cherryjs.com
site_description: Cherry.js is a JavaScript utility library and it can run on both browser and Node.
site_author: Jerry Zou

theme: mkdocs
theme_dir: theme/cherry

pages:
- ['index.md', 'Home']
- ['method.md', 'Method']
