site_name: Cherry.js
site_url: http://cherryjs.com
site_description: Cherry.js is a JavaScript utility library and it can run on both browser and Node.
site_author: Jerry Zou

theme: mkdocs
theme_dir: theme/cherry

pages:
- ['index.md']
- ['examples.md', '简单的例子']
- ['detail.md', '详说Cherry.js']
# - ['method/array.md', '详细文档', 'Array']
# - ['method/object.md', '详细文档', 'Object']
# - ['method/string.md', '详细文档', 'String']
- ['error.md', '错误类型']
- ['about.md', '关于', 'Cherry.js的诞生']
- ['license.md', '关于', '开源协议']
